//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloc
    {
        public int IdBloc { get; set; }
        public string cheminTemplate { get; set; }
        public int IdTypeBloc { get; set; }
        public int IdReference { get; set; }
        public int IdStyle { get; set; }
    
        public virtual Style Style { get; set; }
        public virtual TypeBloc TypeBloc { get; set; }
    }
}
