//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int IdCommentaire { get; set; }
        public string Texte { get; set; }
        public int IdPublication { get; set; }
        public int IdAuteur { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int IdStatut { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual Statut Statut { get; set; }
    }
}
