//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.Notification = new HashSet<Notification>();
            this.Page = new HashSet<Page>();
        }
    
        public int IdMedia { get; set; }
        public string Chemin { get; set; }
        public byte[] C_Image { get; set; }
        public string Description { get; set; }
        public System.DateTime DatePublication { get; set; }
        public int IdStatut { get; set; }
        public int IdAcces { get; set; }
        public int IdTypeMedia { get; set; }
        public int IdAuteur { get; set; }
        public Nullable<int> IdReference { get; set; }
        public Nullable<int> IdTypeBloc { get; set; }
        public Nullable<int> IdPublication { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual TypeBloc TypeBloc { get; set; }
        public virtual TypeMedia TypeMedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Page { get; set; }
    }
}
