//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int IdMessage { get; set; }
        public Nullable<int> IdMessageParent { get; set; }
        public int IdForum { get; set; }
        public string Texte { get; set; }
        public Nullable<int> Popularite { get; set; }
        public Nullable<int> IdStatut { get; set; }
        public int IdAuteur { get; set; }
        public Nullable<System.DateTime> DatePublication { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Statut Statut { get; set; }
        
    }
}
