//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterCodeEntities : DbContext
    {
        public MasterCodeEntities()
            : base("name=MasterCodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acces> Acces { get; set; }
        public virtual DbSet<Bloc> Bloc { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Commentaire> Commentaire { get; set; }
        public virtual DbSet<Forum> Forum { get; set; }
        public virtual DbSet<Langue> Langue { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Messagerie> Messagerie { get; set; }
        public virtual DbSet<MotClef> MotClef { get; set; }
        public virtual DbSet<MotClefCategorie> MotClefCategorie { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<Priorite> Priorite { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<Publicite> Publicite { get; set; }
        public virtual DbSet<Recherche> Recherche { get; set; }
        public virtual DbSet<Statut> Statut { get; set; }
        public virtual DbSet<Style> Style { get; set; }
        public virtual DbSet<Traduction> Traduction { get; set; }
        public virtual DbSet<Trophee> Trophee { get; set; }
        public virtual DbSet<TypeBloc> TypeBloc { get; set; }
        public virtual DbSet<TypeMedia> TypeMedia { get; set; }
        public virtual DbSet<TypePublication> TypePublication { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
