//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int IdNotification { get; set; }
        public string Objet { get; set; }
        public string Texte { get; set; }
        public int IdExpediteur { get; set; }
        public int IdDestinataire { get; set; }
        public Nullable<int> IdPieceJointe { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
    }
}
