//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int IdPage { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public string typePage { get; set; }
        public string Blocs { get; set; }
        public System.DateTime DatePublication { get; set; }
        public System.DateTime DateModification { get; set; }
        public Nullable<int> IdPublication { get; set; }
        public int IdAuteur { get; set; }
        public int IdMaquette { get; set; }
        public int IdCategorie { get; set; }
        public int IdAcces { get; set; }
        public int IdStatut { get; set; }
        public int IdStyle { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Media Media { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual Style Style { get; set; }
    }
}
