//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Commentaire = new HashSet<Commentaire>();
            this.Media = new HashSet<Media>();
            this.Page = new HashSet<Page>();
        }
    
        public int IdPublication { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public string Resume { get; set; }
        public string Texte { get; set; }
        public string Champ1 { get; set; }
        public string Champ2 { get; set; }
        public string Champ3 { get; set; }
        public string Champ4 { get; set; }
        public System.DateTime DatePublication { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public int Popularite { get; set; }
        public string MotsClefs { get; set; }
        public Nullable<int> IdAuteur { get; set; }
        public Nullable<int> IdPublicationParent { get; set; }
        public Nullable<int> IdTypePublication { get; set; }
        public Nullable<int> IdCategorie { get; set; }
        public Nullable<int> IdAcces { get; set; }
        public int IdStatut { get; set; }
        public int IdLangue { get; set; }
    
        public virtual Acces Acces { get; set; }
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentaire> Commentaire { get; set; }
        public virtual Langue Langue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media> Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Page { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Statut Statut { get; set; }
        public virtual TypePublication TypePublication { get; set; }
    }
}
