//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMasterCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traduction
    {
        public int IdTraduction { get; set; }
        public string DefaultTexte { get; set; }
        public string TraductionTexte { get; set; }
        public int IdLangue { get; set; }
    
        public virtual Langue Langue { get; set; }
    }
}
